### ISSUE TITLE
an API suggestion

### ISSUE THREAD

**Issue by oconnor663** [rctcwyvrn/Blake3Java#1]
I'm really glad to see a pure Java port! I see a lot of folks online asking for a Java implementation, and now I can point them to this one.

One API suggestion: Overloading the constructor for the keyed and KDF modes might be a little too surprising. With the KDF mode in particular, someone might pass in a string of data they want to hash, thinking that the alternate constructor is just a convenience wrapper around `update`. (Notably, this _is_ how hasher constructors usually work in Python.) If possible, it might be better to separate the keyed and KDF modes into functions with different names.

By the way, do you have any feedback on the reference implementation, like about any parts that were confusing? (I noticed that what I called `Output`, you called `Node`. That makes sense, and I'll think about it some more.) Did you read Section 5 of [the BLAKE3 paper](https://github.com/BLAKE3-team/BLAKE3-specs/blob/master/blake3.pdf)? Was it helpful? Did you notice the [test vectors](https://github.com/BLAKE3-team/BLAKE3/blob/master/test_vectors/test_vectors.json), and is there another data format we could convert them to that would be more useful?

**Comment by rctcwyvrn** [comment]
> If possible, it might be better to separate the keyed and KDF modes into functions with different names

Yea I also thought it would be an issue but was just hoping people would read the javadoc, which probably isn't the best idea. I'll fix it up later today

> By the way, do you have any feedback on the reference implementation, like about any parts that were confusing?

The reference implementation was easy to work with, the only confusion was because of language features that are in rust but not in java (like slices). If the goal was to make it 100% readable to anyone then maybe doing dumb loops like I did would be better. Despite that, even without any rust or hash implementing experience, I managed to write most of my implementation correctly just based on the reference so good job with that.

>  (I noticed that what I called Output, you called Node. That makes sense, and I'll think about it some more.) 

I called the class Node because Output in my mind would be something that was generated once and returned as the result/used to generate the result, and Node made more sense to me.

> Did you read Section 5 of the BLAKE3 paper? Was it helpful? 

I didn't, but I wish I had done a bit more reading beforehand, especially Section 5.

>  Did you notice the test vectors, and is there another data format we could convert them to that would be more useful?

I even took a look in that exact folder and at the code... how did I miss the json...

**Comment by oconnor663** [comment]
> I even took a look in that exact folder and at the code... how did I miss the json...

I'll link to the JSON from the README. Hopefully that'll make it easier to find.

**Comment by rctcwyvrn** [comment]
https://github.com/rctcwyvrn/blake3/commit/420245a1c22f3ac2934e0cdd6b939c903a3ca912 Fixed the API

**Comment by oconnor663** [comment]
Thanks for responding so quickly!

**Comment by rctcwyvrn** [comment]
No problem! Thanks for the feedback. It definitely surprised me to see one of the official devs show up in my repo :)
